export const browserCoreExamples = [
  "thinkfleet browser status",
  "thinkfleet browser start",
  "thinkfleet browser stop",
  "thinkfleet browser tabs",
  "thinkfleet browser open https://example.com",
  "thinkfleet browser focus abcd1234",
  "thinkfleet browser close abcd1234",
  "thinkfleet browser screenshot",
  "thinkfleet browser screenshot --full-page",
  "thinkfleet browser screenshot --ref 12",
  "thinkfleet browser snapshot",
  "thinkfleet browser snapshot --format aria --limit 200",
  "thinkfleet browser snapshot --efficient",
  "thinkfleet browser snapshot --labels",
];

export const browserActionExamples = [
  "thinkfleet browser navigate https://example.com",
  "thinkfleet browser resize 1280 720",
  "thinkfleet browser click 12 --double",
  'thinkfleet browser type 23 "hello" --submit',
  "thinkfleet browser press Enter",
  "thinkfleet browser hover 44",
  "thinkfleet browser drag 10 11",
  "thinkfleet browser select 9 OptionA OptionB",
  "thinkfleet browser upload /tmp/file.pdf",
  'thinkfleet browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "thinkfleet browser dialog --accept",
  'thinkfleet browser wait --text "Done"',
  "thinkfleet browser evaluate --fn '(el) => el.textContent' --ref 7",
  "thinkfleet browser console --level error",
  "thinkfleet browser pdf",
];
