name: Bug Report
description: Report a problem or unexpected behavior.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to trigger the bug.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: install-method
    attributes:
      label: Install method
      options:
        - npm / pnpm (local)
        - Docker (self-hosted)
        - ThinkFleet Cloud (SaaS)
        - npx (one-shot)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Engine version
      description: "Run: thinkfleet --version"
      placeholder: "2026.x.x"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "macOS 15.3 / Ubuntu 24.04 / Windows 11"
    validations:
      required: true

  - type: input
    id: node
    attributes:
      label: Node.js version
      description: "Run: node --version"
      placeholder: "v22.x.x"

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant logs or add screenshots. Redact any secrets.
      render: shell
