name: Feature Request
description: Suggest an idea or improvement.
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion. Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or opportunity
      description: Describe the problem you are trying to solve or the opportunity you see.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: What would you like ThinkFleet Engine to do?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you have considered?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, or related issues.
