name: ThinkFleet
options:
  bundleIdPrefix: com.thinkfleet
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"

settings:
  base:
    SWIFT_VERSION: "6.0"

packages:
  ThinkFleetKit:
    path: ../shared/ThinkFleetKit
  Swabble:
    path: ../../Swabble
  SocketIO:
    url: https://github.com/socketio/socket.io-client-swift
    from: "16.1.1"

schemes:
  ThinkFleet:
    shared: true
    build:
      targets:
        ThinkFleet: all
    test:
      targets:
        - ThinkFleetTests

targets:
  ThinkFleet:
    type: application
    platform: iOS
    sources:
      - path: Sources
    dependencies:
      - package: ThinkFleetKit
      - package: ThinkFleetKit
        product: ThinkFleetChatUI
      - package: ThinkFleetKit
        product: ThinkFleetProtocol
      - package: Swabble
        product: SwabbleKit
      - package: SocketIO
        product: SocketIO
      - sdk: AppIntents.framework
    preBuildScripts:
      - name: SwiftFormat (lint)
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftformat >/dev/null 2>&1; then
            echo "error: swiftformat not found (brew install swiftformat)" >&2
            exit 1
          fi
          swiftformat --lint --config "$SRCROOT/../../.swiftformat" \
            --filelist "$SRCROOT/SwiftSources.input.xcfilelist"
      - name: SwiftLint
        basedOnDependencyAnalysis: false
        inputFileLists:
          - $(SRCROOT)/SwiftSources.input.xcfilelist
        script: |
          set -euo pipefail
          export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"
          if ! command -v swiftlint >/dev/null 2>&1; then
            echo "error: swiftlint not found (brew install swiftlint)" >&2
            exit 1
          fi
          swiftlint lint --config "$SRCROOT/.swiftlint.yml" --use-script-input-file-lists
    settings:
      base:
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: Y5PE65HELJ
        PRODUCT_BUNDLE_IDENTIFIER: ai.thinkfleet.thinkfleetAI
        PROVISIONING_PROFILE_SPECIFIER: "bot.molt.ios Development"
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_APPINTENTS_METADATA: NO
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: ThinkFleet
        CFBundleIconName: AppIcon
        CFBundleShortVersionString: "2026.1.27-beta.1"
        CFBundleVersion: "20260126"
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - audio
        NSLocalNetworkUsageDescription: ThinkFleet discovers and connects to your ThinkFleet gateway on the local network.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoadsInWebContent: true
        NSBonjourServices:
          - _thinkfleet-gw._tcp
        NSCameraUsageDescription: ThinkFleet can capture photos or short video clips when requested via the gateway.
        NSLocationWhenInUseUsageDescription: ThinkFleet uses your location when you allow location sharing.
        NSLocationAlwaysAndWhenInUseUsageDescription: ThinkFleet can share your location in the background when you enable Always.
        NSMicrophoneUsageDescription: ThinkFleet needs microphone access for voice wake.
        NSSpeechRecognitionUsageDescription: ThinkFleet uses on-device speech recognition for voice wake.
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  ThinkFleetTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: ThinkFleet
      - package: Swabble
        product: SwabbleKit
      - sdk: AppIntents.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.thinkfleet.thinkfleetAI.tests
        SWIFT_VERSION: "6.0"
        SWIFT_STRICT_CONCURRENCY: complete
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/ThinkFleet.app/ThinkFleet"
        BUNDLE_LOADER: "$(TEST_HOST)"
    info:
      path: Tests/Info.plist
      properties:
        CFBundleDisplayName: ThinkFleetTests
        CFBundleShortVersionString: "2026.1.27-beta.1"
        CFBundleVersion: "20260126"
