#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${THINKFLEETBOT_INSTALL_E2E_IMAGE:-thinkfleetbot-install-e2e:local}"
INSTALL_URL="${THINKFLEETBOT_INSTALL_URL:-https://molt.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
THINKFLEETBOT_E2E_MODELS="${THINKFLEETBOT_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e THINKFLEETBOT_INSTALL_URL="$INSTALL_URL" \
  -e THINKFLEETBOT_INSTALL_TAG="${THINKFLEETBOT_INSTALL_TAG:-latest}" \
  -e THINKFLEETBOT_E2E_MODELS="$THINKFLEETBOT_E2E_MODELS" \
  -e THINKFLEETBOT_INSTALL_E2E_PREVIOUS="${THINKFLEETBOT_INSTALL_E2E_PREVIOUS:-}" \
  -e THINKFLEETBOT_INSTALL_E2E_SKIP_PREVIOUS="${THINKFLEETBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
